### ISSUE TITLE
Angular 1.3.x support

### ISSUE THREAD

**Issue by Murwa** [kstam/ng-scroll-repeat#2]
@kstam is this compatible with angular 1.3.x? It doesn't seem to work for me

**Comment by kstam** [comment]
Hi Murwa,

Thanks a lot for your question and sorry for delaying to reply. 

The library should work perfectly with angular 1.3.x. Since you raised the issue though, I had to test it. So I created an example for the lib using angular 1.3.14.

You can see the example live here: https://rawgit.com/kstam/ng-scroll-repeat/master/example/index.html
The source code for the example is here: https://github.com/kstam/ng-scroll-repeat/blob/master/example/index.html

Let me know if your problem is resolved, and thanks again for using the lib

**Comment by kstam** [comment]
Closing this issue as there has been no reply for some time.

**Comment by Murwa** [comment]
hey @kstam apologies for late reply and thanks for responding. I'll check on your code, maybe I'd missed something;
